#=====  GitHelp - START  ===== !!! MAKE ALL MODIFICATIONS ABOVE THIS LINE !!!
export GITHELP_HOME=~/GitHelp

if [ -a ~/.githelp_profile ] ; then
    source ~/.githelp_profile
else
    printf "\nGitHelp installation:\n"
    printf "    No Origins have been cloned.\n"
    printf "    Use ghCO to Clone an Origin (a developer fork).\n\n"
fi

alias gh="$GITHELP_HOME/ghHELP.sh"
alias ghEDITOR="$GITHELP_HOME/ghEDITOR.sh"
alias ghVERSION="$GITHELP_HOME/ghVERSION.sh"

###  Convenience Commands  ######
alias ghBUD="$GITHELP_HOME/ghBrowseUpstreamDevelopment.sh"
alias ghBrowseUpstreamDevelopment=ghBUD
alias ghS="git status"
alias ghAA="git add -A"
alias ghACP="$GITHELP_HOME/ghAddCommitPush.sh"
alias ghP="git push"
alias ghL="git log"
alias ghLRA="$GITHELP_HOME/ghLintReportForAndroid.sh"
alias ghB="git branch"
alias ghCancelMerge="git reset --merge"
alias ghClean="$GITHELP_HOME/ghClean.sh"
alias ghRH="$GITHELP_HOME/ghResetHard.sh"
alias ghResetHard="$GITHELP_HOME/ghResetHard.sh"

###  Repository Commands  ######
alias ghROOT="cd $GIT_ROOT; pwd; $GITHELP_HOME/ghBranchList.sh"
alias ghCD="ghROOT"

xxChangeRepository() {
  $GITHELP_HOME/ghChangeRepo.sh $@
  if [[ "$?" -eq 0 ]] ; then
    source ~/.bash_profile
    cd $GIT_ROOT; pwd; $GITHELP_HOME/ghBranchList.sh
  fi
}
xxCONFIG() {
  $GITHELP_HOME/ghCONFIG.sh $@
  if [[ "$?" -eq 0 ]] ; then
    source ~/.bash_profile
    cd $GIT_ROOT; pwd; $GITHELP_HOME/ghBranchList.sh
  fi
}
xxCloneOrigin() {
  $GITHELP_HOME/ghCloneOrigin.sh $@
  if [[ "$?" -eq 0 ]] ; then
    source ~/.bash_profile
    cd $GIT_ROOT; pwd; $GITHELP_HOME/ghBranchList.sh
  fi
}

alias ghCR=xxChangeRepository
alias ghChangeRepo=xxChangeRepository
alias ghCO=xxCloneOrigin
alias ghCloneOrigin=xxCloneOrigin
alias ghSA="$GITHELP_HOME/ghStaticAnalysis.sh"
alias ghStaticAnalysis="$GITHELP_HOME/ghStaticAnalysis.sh"
alias ghCONFIG=xxCONFIG
alias ghCD=ghROOT

###  A  ######
alias ghNMBD="$GITHELP_HOME/ghNewMiscBranchFromDevelopment.sh"
alias ghNewMiscBranchDevelopment="$GITHELP_HOME/ghNewMiscBranchFromDevelopment.sh"
alias ghNMBE="$GITHELP_HOME/ghNewMiscBranchFromEpic.sh"
alias ghNewMiscBranchEpic="$GITHELP_HOME/ghNewMiscBranchFromEpic.sh"
alias ghNMBR="$GITHELP_HOME/ghNewMiscBranchFromRelease.sh"
alias ghNewMiscBranchRrelease="$GITHELP_HOME/ghNewMiscBranchFromRelease.sh"
alias ghNMBS="$GITHELP_HOME/ghNewMiscBranchFromSHA.sh"
alias ghNewMiscBranchSha="$GITHELP_HOME/ghNewMiscBranchFromSHA.sh"
alias ghNDMB="$GITHELP_HOME/ghNewDerivedMiscBranch.sh"
alias ghNewDerivedMiscBranch="$GITHELP_HOME/ghNewDerivedMiscBranch.sh"
alias ghNMBM="$GITHELP_HOME/ghNewMiscBranch.sh"
alias ghCMB="$GITHELP_HOME/ghCheckoutMiscBranch.sh"
alias ghDMB="$GITHELP_HOME/ghDestroyMiscBranch.sh"
alias ghDestroyMiscBranch="$GITHELP_HOME/ghDestroyMiscBranch.sh"
alias ghDCB="$GITHELP_HOME/ghDestroyCurrentBranch.sh"
alias ghDestroyCurrentBranch="$GITHELP_HOME/ghDestroyCurrentBranch.sh"

###  B  ######
alias ghNTBD="$GITHELP_HOME/ghNewTicketBranchFromDevelopment.sh"
alias ghNewTicketBranchDevelopment="$GITHELP_HOME/ghNewTicketBranchFromDevelopment.sh"
alias ghNTBE="$GITHELP_HOME/ghNewTicketBranchFromEpic.sh"
alias ghNewTicketBranchEpic="$GITHELP_HOME/ghNewTicketBranchFromEpic.sh"
alias ghNTBR="$GITHELP_HOME/ghNewTicketBranchFromRelease.sh"
alias ghNewTicketBranchRelease="$GITHELP_HOME/ghNewTicketBranchFromRelease.sh"
alias ghNTBS="$GITHELP_HOME/ghNewTicketBranchFromSHA.sh"
alias ghNewTicketBranchSha="$GITHELP_HOME/ghNewTicketBranchFromSHA.sh"
alias ghNDTB="$GITHELP_HOME/ghNewDerivedTicketBranch.sh"
alias ghNewDerivedTicketBranch="$GITHELP_HOME/ghNewDerivedTicketBranch.sh"
alias ghRT="$GITHELP_HOME/ghReviewTicket.sh"
alias ghReviewTicket="$GITHELP_HOME/ghReviewTicket.sh"
alias ghCTB="$GITHELP_HOME/ghCheckoutTicketBranch.sh"
alias ghDTB="$GITHELP_HOME/ghDestroyTicketBranch.sh"
alias ghDestroyTicketBranch="$GITHELP_HOME/ghDestroyTicketBranch.sh"

###  C  ######
alias ghUBUD="$GITHELP_HOME/ghUpdateBranchWithUpstreamDevelopment.sh"
alias ghUpdateBranchUpstreamDevelopment="$GITHELP_HOME/ghUpdateBranchWithUpstreamDevelopment.sh"
alias ghUBUR="$GITHELP_HOME/ghUpdateBranchWithUpstreamRelease.sh"
alias ghUpdateBranchUpstreamRelease="$GITHELP_HOME/ghUpdateBranchWithUpstreamRelease.sh"
alias ghUBUE="$GITHELP_HOME/ghUpdateBranchWithUpstreamEpic.sh"
alias ghUpdateBranchUpstreamEpic="$GITHELP_HOME/ghUpdateBranchWithUpstreamEpic.sh"
alias ghRTS="$GITHELP_HOME/ghRevertCurrentBranchToSha.sh"
alias ghRevertToSha="$GITHELP_HOME/ghRevertCurrentBranchToSha.sh"

###  D  ######
alias ghNPRD="$GITHELP_HOME/ghNewPullRequestForDevelopment.sh"
alias ghNewPullRequestDevelopment="$GITHELP_HOME/ghNewPullRequestForDevelopment.sh"
alias ghNPRR="$GITHELP_HOME/ghNewPullRequestForRelease.sh"
alias ghNewPullRequestRelease="$GITHELP_HOME/ghNewPullRequestForRelease.sh"
alias ghNPRE="$GITHELP_HOME/ghNewPullRequestForEpic.sh"
alias ghNewPullRequestEpic="$GITHELP_HOME/ghNewPullRequestForEpic.sh"
alias ghNPRFTB="$GITHELP_HOME/ghNewPullRequestForForkTicketBranch.sh"
alias ghNewPullRequestForkTicketBranch="$GITHELP_HOME/ghNewPullRequestForForkTicketBranch.sh"
alias ghNPRFMB="$GITHELP_HOME/ghNewPullRequestForFork.sh"
alias ghNewPullRequestForkMiscBranch="$GITHELP_HOME/ghNewPullRequestForFork.sh"
alias ghRPRU="$GITHELP_HOME/ghReviewPullRequestsForUpstream.sh"
alias ghReviewPullRequestsUpstream="$GITHELP_HOME/ghReviewPullRequestsForUpstream.sh"
alias ghRPRF="$GITHELP_HOME/ghReviewPullRequestsForFork.sh"
alias ghReviewPullRequestsFork="$GITHELP_HOME/ghReviewPullRequestsForFork.sh"
alias ghFPRB="$GITHELP_HOME/ghFetchPullRequestBranch.sh"
alias ghFetchPullRequestBranch="$GITHELP_HOME/ghFetchPullRequestBranch.sh"


alias ghNMRD="$GITHELP_HOME/ghNewMergeRequestForDevelopment.sh"
alias ghNewMergeRequestDevelopment="$GITHELP_HOME/ghNewMergeRequestForDevelopment.sh"
alias ghNMRR="$GITHELP_HOME/ghNewMergeRequestForRelease.sh"
alias ghNewMergeRequestRelease="$GITHELP_HOME/ghNewMergeRequestForRelease.sh"
alias ghNMRE="$GITHELP_HOME/ghNewMergeRequestForEpic.sh"
alias ghNewMergeRequestEpic="$GITHELP_HOME/ghNewMergeRequestForEpic.sh"
alias ghNMRFTB="$GITHELP_HOME/ghNewMergeRequestForForkTicketBranch.sh"
alias ghNewMergeRequestForkTicketBranch="$GITHELP_HOME/ghNewMergeRequestForForkTicketBranch.sh"
alias ghNMRFMB="$GITHELP_HOME/ghNewMergeRequestForFork.sh"
alias ghNewMergeRequestForkMiscBranch="$GITHELP_HOME/ghNewMergeRequestForFork.sh"

###  E  ######
alias ghLOB="$GITHELP_HOME/ghListOriginBranches.sh"
alias ghListOriginBranches="$GITHELP_HOME/ghListOriginBranches.sh"
alias ghFOB="$GITHELP_HOME/ghFetchOriginBranch.sh"
alias ghFetchOriginBranch="$GITHELP_HOME/ghFetchOriginBranch.sh"
alias ghLUB="$GITHELP_HOME/ghListUpstreamBranches.sh"
alias ghListUpstreamBranches="$GITHELP_HOME/ghListUpstreamBranches.sh"

###  F  ######
alias ghLFB="$GITHELP_HOME/ghListForkBranches.sh"
alias ghLFD="$GITHELP_HOME/ghListForkDevelopers.sh"
alias ghListForkBranches="$GITHELP_HOME/ghListForkBranches.sh"
alias ghFFTB="$GITHELP_HOME/ghFetchForkTicketBranch.sh"
alias ghFetchForkTicketBranch="$GITHELP_HOME/ghFetchForkTicketBranch.sh"
alias ghFFMB="$GITHELP_HOME/ghFetchForkMiscBranch.sh"
alias ghFetchForkMiscBranch="$GITHELP_HOME/ghFetchForkMiscBranch.sh"
alias ghUBFTB="$GITHELP_HOME/ghUpdateBranchWithForkTicketBranch.sh"
alias ghUpdateBranchForkTicketBranch="$GITHELP_HOME/ghUpdateBranchWithForkTicketBranch.sh"
alias ghUBFMB="$GITHELP_HOME/ghUpdateBranchWithForkBranch.sh"
alias ghUpdateBranchForkMiscBranch="$GITHELP_HOME/ghUpdateBranchWithForkBranch.sh"
###  Need new category ######
alias ghLFRB="$GITHELP_HOME/ghListForeignRepoBranches.sh"
alias ghListForeignRepoBranches="$GITHELP_HOME/ghListForeignRepoBranches.sh"

###  G  ######
alias ghFUDB="$GITHELP_HOME/ghFetchUpstreamDevelopmentBranch.sh"
alias ghFetchUpstreamDevelopmentBranch="$GITHELP_HOME/ghFetchUpstreamDevelopmentBranch.sh"
alias ghLRB="$GITHELP_HOME/ghListReleaseBranches.sh"
alias ghListReleaseBranches="$GITHELP_HOME/ghListReleaseBranches.sh"
alias ghLEB="$GITHELP_HOME/ghListEpicBranches.sh"
alias ghListEpicBranches="$GITHELP_HOME/ghListEpicBranches.sh"

###  H  ######
alias ghCUF="$GITHELP_HOME/ghCleanUntrackedFiles.sh"
alias ghCleanUntrackedFiles="$GITHELP_HOME/ghCleanUntrackedFiles.sh"
alias ghCUFCB="$GITHELP_HOME/ghCleanUntrackedFilesAndCheckoutBranch.sh"
alias ghCleanUntrackedFilesCheckoutBranch="$GITHELP_HOME/ghCleanUntrackedFilesAndCheckoutBranch.sh"
alias ghSCDC="$GITHELP_HOME/ghStashChangesAndDropAndClean.sh"
alias ghStashChangesDropClean="$GITHELP_HOME/ghStashChangesAndDropAndClean.sh"

###  J  ######
alias ghCPSHA="$GITHELP_HOME/ghCherryPickSha.sh"
alias ghCherryPickSha="$GITHELP_HOME/ghCherryPickSha.sh"
alias ghLMC="$GITHELP_HOME/ghListMergeConflicts.sh"
alias ghListMergeConflicts="$GITHELP_HOME/ghListMergeConflicts.sh"

###  K  ######
alias ghCW="$GITHELP_HOME/ghCloneWiki.sh"
alias ghCWFGG="$GITHELP_HOME/ghCloneWikiFromGitlabGroup.sh"
alias ghPW="$GITHELP_HOME/ghPullWiki.sh"
alias ghPWFGG="$GITHELP_HOME/ghPullWikiFromGitlabGroup.sh" 
alias ghUW="$GITHELP_HOME/ghUpdateWiki.sh"
alias ghUWFGG="$GITHELP_HOME/ghUpdateWikiFromGitlabGroup.sh"

###  M  ######
alias ghREMOTE="git remote -v"
alias ghPLBNOO="$GITHELP_HOME/ghPruneLocalBranchesNotOnOrigin.sh"
alias ghPruneLocalBranchesNotOnOrigin="$GITHELP_HOME/ghPruneLocalBranchesNotOnOrigin.sh"
alias ghPAOBED="$GITHELP_HOME/ghPruneAllOriginBranchesExceptDevelopment.sh"
alias ghPruneAllOriginBranchesExceptDevelopment="$GITHELP_HOME/ghPruneAllOriginBranchesExceptDevelopment.sh"
alias ghPOB="$GITHELP_HOME/ghPruneAllOriginBranchesExceptDevelopment.sh"
alias ghPruneOriginBranches="$GITHELP_HOME/ghPruneAllOriginBranchesExceptDevelopment.sh"
alias ghPOBNOL="$GITHELP_HOME/ghPruneOriginBranchesNotOnLocalExceptDevelopment.sh"
alias ghPruneOriginBranchesNotOnLocal="$GITHELP_HOME/ghPruneOriginBranchesNotOnLocalExceptDevelopment.sh"
alias ghPLB="$GITHELP_HOME/ghPruneLocalBranchesExceptDevelopment.sh"
alias ghPruneLocalBranches="$GITHELP_HOME/ghPruneLocalBranchesExceptDevelopment.sh" 
alias ghCarWash="$GITHELP_HOME/ghCarWash.sh"
#!!!!!!!!!!  DO NOT ADD ANYTHING BELOW THIS LINE  !!!!!!!!!!!!!!
